@Api_HostAddress = http://localhost:5277

GET {{Api_HostAddress}}/products/
Accept: application/json

###

POST {{Api_HostAddress}}/products/
Content-Type: application/json

{ "name":  " 2 test", "categoryId":  6}

###

PUT {{Api_HostAddress}}/products/2
Content-Type: application/json

{ "id": 2, "name":  "updated", "categoryId":  23}